FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install python3.10 -y
RUN apt-get install python3-pip -y
WORKDIR /app
COPY . .
RUN pip3.10 install -r requirements.txt
EXPOSE 80
CMD ["python3.10","./src/main.py"]

