# Usar una imagen base de Ubuntu 22.04
FROM ubuntu:22.04

# Evitar que los comandos de apt-get pidan confirmación interactiva
ENV DEBIAN_FRONTEND=noninteractive

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar primero el archivo de requerimientos para optimizar el cache de capas
COPY requirements.txt .

# Actualizar el gestor de paquetes, instalar Python 3.10 y pip,
# y finalmente instalar las dependencias de Python.
RUN apt-get update && \
    apt-get install -y python3.10 python3-pip && \
    pip3 install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación al directorio de trabajo
COPY . .

# Establecer variables de entorno por defecto
ENV PYTHONPATH=/app
ENV ORION_URL=http://orion:1026

EXPOSE 8080
# Comando para ejecutar la aplicación usando python3.10
CMD ["python3.10", "app.py"]
